---
title: "Exploration Ideas"
format: html
---
https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-29/readme.md

look into rev and expend for div 1
```{r}
library(tidyverse)
library(dplyr)
# bring in the data 
tuesdata <- tidytuesdayR::tt_load('2022-03-29')
tuesdata <- tidytuesdayR::tt_load(2022, week = 13)
CollegiateSports <- tuesdata$sports

# filter so its only Division 1 sports 
div1 <- CollegiateSports |> filter(grepl('NCAA Division I', classification_name)) |> filter(classification_code <= 3)
#str detect
# check that after I, its not another I, or exactly one I

# figured out that classifications for all D1 sports are either 1, 2, or 3
div1_smaller <- div1 |> select(1,3,7,8,20:28)

# selected only the columns that I'm interested in. 

div1_rev_expend <- div1_smaller |> select(1:4, 9, 12, 13)

```


how the trend changes over time and including a graphic
- I want to make an option where you'll be able to select a school and be able to see a barplot of their total rev value and total expend value over the last 5 years 
```{r}
library(scales)
# start this with one school at a time 
# start with University of Colorado Boulder
UC_Boulder <- div1_rev_expend |> filter(institution_name == "University of Colorado Boulder") |>
  filter(!is.na(total_rev_menwomen), !is.na(total_exp_menwomen)) |>
  group_by(year) |>
  summarise(total_rev = sum(total_rev_menwomen), total_exp = sum(total_exp_menwomen))

## institution_name is set to an object, that will become input in shiny 
## use str_glue to pass object with school name through 
## use functions 


UC_Boulder2 <- UC_Boulder |> pivot_longer(cols = c(total_rev, total_exp),
                           names_to = "Type", values_to = "Dollars")

ggplot(data = UC_Boulder2, aes(x = year, y = Dollars, fill = Type)) +
  geom_col(position = "dodge") +
  scale_y_continuous("Dollars",
    breaks = scales::breaks_extended(8),
    labels = scales::label_dollar()) +
  labs(title = "Total Revenue and Expenditure for Sports\nat CU Boulder 2015-2019")


# or do all schools in my roughly created D1 group
div1_collapsed <- div1_rev_expend |> filter(!is.na(total_rev_menwomen), !is.na(total_exp_menwomen)) |>
group_by(institution_name, year) |> summarise(total_rev = sum(total_rev_menwomen), total_exp = sum(total_exp_menwomen))

div1_pivot <- div1_collapsed |> pivot_longer(cols = c(total_rev, total_exp),
                           names_to = "Type", values_to = "Dollars")

ggplot(data = div1_pivot, aes(x = year, y = Dollars, fill = Type)) +
  geom_col(position = "dodge") +
  facet_wrap(~institution_name) +
    scale_y_continuous("Dollars",
    breaks = scales::breaks_extended(8),
    labels = scales::label_dollar())
## this is too many, try top 10 schools for rev

top10_rev <- div1_rev_expend |> filter(!is.na(total_rev_menwomen), !is.na(total_exp_menwomen)) |>
group_by(institution_name) |> summarise(total_rev = sum(total_rev_menwomen), total_exp = sum(total_exp_menwomen)) |>
  arrange(desc(total_rev)) |> slice(1:10)

## create a vector with names of the universities from top 10

```

2/28 meeting with Ramler 
Goal is making a good shiny app 
find a goal of analysis
- break down by division and sport or gender 

```{r}
# figure out how to select one school using it as an object?
## I want the filter statement to be user interaction on the shiny app 
school_name <- "University of Colorado Boulder"

school_select_rev_expend <- div1_rev_expend |> filter(institution_name == school_name) |>
  filter(!is.na(total_rev_menwomen), !is.na(total_exp_menwomen)) |>
  group_by(institution_name, year) |>
  summarise(total_rev = sum(total_rev_menwomen), total_exp = sum(total_exp_menwomen)) |>
  pivot_longer(cols = c(total_rev, total_exp),
                           names_to = "Type", values_to = "Dollars")

ggplot(data = school_select_rev_expend, aes(x = year, y = Dollars, fill = Type)) +
  geom_col(position = "dodge") +
  scale_y_continuous("Dollars",
    breaks = scales::breaks_extended(8),
    labels = scales::label_dollar()) +
  labs(title = str_glue("Total Revenue and Expenditure for Sports\nat {school_name}")) +
  theme_minimal() +
  scale_fill_viridis_d()
```

```{r}
library(datasets)
WorldPhones

div1_rev_expend |> pull(institution_name)
```




